### ISSUE TITLE
Issues with iOS Version dynamic not supported 

### ISSUE THREAD

**Issue by ljbdelacruz** [DevCycleHQ/flutter-client-sdk#154]
Issues:
its causing the app to crash/app freezing after few minutes of usage on the Xcode logs its says Streaming Failure dynamic variable issues with the latest iOS Version

![Screenshot 2024-05-18 at 7 24 12 AM](https://uploads.linear.app/ad49e6ed-1963-4ad4-95b3-bb8fecf2ff14/1e4f5656-c82e-445e-b788-de78fd8bc4a0/3facb735-6a7d-4af4-bc6a-421592cbbaaf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FkNDllNmVkLTE5NjMtNGFkNC05NWIzLWJiOGZlY2YyZmYxNC8xZTRmNTY1Ni1jODJlLTQ0NWUtYjc4OC1kZTc4ZmQ4YmM0YTAvM2ZhY2I3MzUtNmE3ZC00YWY0LWJjNmEtNDIxNTkyY2JiYWFmIiwiaWF0IjoxNzE1OTk1NDczLCJleHAiOjMzMjg2NTU1NDczfQ.CKKyK1_PQwflD0m6BUsPGsPj-tQM4PdhtCPoyuKt77M "=528x")

**Comment by kaushalkapasi** [comment]
Hi @ljbdelacruz could you provide a code snippet where you are initializing & using the variables in your code? It'll help us narrow the issue down.

Thanks!

**Comment by ljbdelacruz** [comment]
devcycle_flutter_client_sdk: ^1.8.0

`DevCycleClient _setupDevCycleClient(String userId){
  return DevCycleClientBuilder()
      .sdkKey(devCycleSDKKey ?? "")
      .user(DevCycleUserBuilder().userId(userId).build())
      .options(DevCycleOptionsBuilder().logLevel(LogLevel.info).build())
      .build();
  }`

`var client = _setupDevCycleClient(userId);
      try{
        bool scanDetailedInfoValue = await client.variableValue('scan-detailed-info', false);
        if (scanDetailedInfoValue) {
          // Put feature code here, or launch feature from here
          return const Right(true);
        } else {
          // Put feature code here, or launch feature from here
          return const Right(false);
        }
      } catch(e){
        return Left(DevCycleFailure());
      }`

**Comment by kaushalkapasi** [comment]
Thanks! Let me take this back and review with the team.

**Comment by kaushalkapasi** [comment]
Hey @ljbdelacruz, this issue should be resolved with our `1.8.1` release, specifically with this PR https://github.com/DevCycleHQ/flutter-client-sdk/pull/146. If possible could you share your entry in the `pubspec.lock` for the `devcycle_flutter_sdk` and the version it is using?

**Comment by leslie-lau** [comment]
Hi @ljbdelacruz could you confirm if you were on version `1.8.1` and/or share your `pubspec.lock` file with us to confirm the version?

**Comment by kaushalkapasi** [comment]
Resolved by updating `pubspec.lock` file to use a version newer than `1.8.1`
