### ISSUE TITLE
[Dependencies] Update Logger on 2.x.x

### ISSUE THREAD

**Issue by md-weber** [DevCycleHQ/flutter-client-sdk#161]
The logger dependency is quite outdated and should be upgraded.

**Comment by kaushalkapasi** [comment]
Hey @md-weber, thanks for raising this issue. We'll get this addressed shortly!

**Comment by kaushalkapasi** [comment]
Hey @md-weber, just released `v1.9.1` with some dependency updates. Let me know if this addresses the issue!

**Comment by md-weber** [comment]
Thanks a lot! ^^ works like a charm
